<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Brian Cervantes Alvarez – us_medical_insurance_costs_v2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Brian Cervantes Alvarez</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html">
 <span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../LinkedIn"><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">



<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>title: <span class="st">"U.S. Medical Insurance Costs"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>author: <span class="st">"Brian Cervantes Alvarez"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>date: <span class="st">"2022-07-14"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>categories: [python, healthcare, analysis, stats]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>image: <span class="st">"health_ins.jepg"</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="op">---</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="u.s.-medical-insurance-costs" class="level1">
<h1>U.S. Medical Insurance Costs</h1>
<section id="purpose-of-this-project" class="level2">
<h2 class="anchored" data-anchor-id="purpose-of-this-project">Purpose of this Project</h2>
<p>This is a portolifo project for the medical industry to demonstrate the ability to provide visualizations and statistical inferences when given a cleaned up data set. In this case, I am looking into the U.S. Medical Insurance Costs sample data set that was provided by Codecademy’s Data Scientist: Inference Specialist Path: https://www.kaggle.com/datasets/mirichoi0218/insurance</p>
<p>Here are a few questions I formulated before diving into the data set: <em>What single component causes the most increase in insurance costs? What variables play a role in increasing or decreasing insurance costs? What would be the ideal individual to minimize the cost of medical insurance?</em></p>
<p>I immediately identified <strong>smoker</strong> as being a key variable to analyze their individual costs. Plus, I dive into the difference of between male and female insurance costs for both smokers and nonsmokers.</p>
<p><strong>If you wish to skip towards the results portion, feel free to scroll down and have a quick read! Interesting results were found.</strong></p>
<section id="set-up-and-importing-the-data" class="level3">
<h3 class="anchored" data-anchor-id="set-up-and-importing-the-data">Set Up and Importing the Data</h3>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#read in the csv file</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'insurance.csv'</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520</code></pre>
</div>
</div>
</section>
</section>
<section id="analyzing-smoker-insurance-costs" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-smoker-insurance-costs">Analyzing Smoker Insurance Costs</h2>
<p>We want to know what influences the cost of insurance. What causes an individual to pay more for their insurance? We can infer that being a smoker will drastically increase their out of pocket medical insurance expenses.</p>
<p>I take a look into how many smokers we have in this data set. Then, I take a quick look into the smokers’ distribution of charges and show a boxplot to visualize the insurance cost quartiles. Next, I dive into using some statistics such as finding the min, max, mean, median, etc. I follow up by seperating male and female smokers and seeing if there’s a drastic change in their expenses.</p>
<section id="histogram-plot-of-smokers-vs-nonsmokers" class="level3">
<h3 class="anchored" data-anchor-id="histogram-plot-of-smokers-vs-nonsmokers">Histogram Plot of Smokers vs Nonsmokers</h3>
<ul>
<li>Smoker Count: 274</li>
<li>Nonsmoker Count: 1064</li>
</ul>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#while a histogram is not necessary, it can really show in the visual count of smokers vs nonsmokers</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize <span class="op">=</span> (<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(df.smoker)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Smoker vs Nonsmoker Count'</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'smoker_vs_nonsmoker_count.png'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>plt.clf()</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co">#num_smokers = df.smoker.value_counts()['yes']</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">#num_nonsmokers = df.smoker.value_counts()['no']</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co">#print("Exact number of smokers: {num_smokers}".format(num_smokers = num_smokers))</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co">#print("Exact number of nonsmokers: {num_nonsmokers}".format(num_nonsmokers = num_nonsmokers))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-4-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 432x288 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="boxplot-and-histogram-distribution-of-insurance-costs-for-smokers" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-and-histogram-distribution-of-insurance-costs-for-smokers">Boxplot and Histogram Distribution of Insurance Costs for Smokers</h3>
<p>The interquartile range is $20,125.33. Very high spread from the first and third interquartiles.</p>
<p>Now, notice that we have a bimodal distribution. This means that there is a variable in the data set that is drastically affecting the insurance cost. Since there is two “humps” we must identify the component that causes a further jump in insurance costs for those who smoke.</p>
<p>What could cause this? - Region? - Bmi? - Sex? - Children? - Age?</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df_smokers <span class="op">=</span> df[df.smoker <span class="op">==</span> <span class="st">'yes'</span>]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_smokers.head())</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>IQR <span class="op">=</span> stats.iqr(df_smokers.charges, interpolation <span class="op">=</span> <span class="st">'midpoint'</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">#print(round(IQR,2))</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">2</span>,figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">10</span>))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co">#boxplot</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>sns.boxplot(y <span class="op">=</span> df_smokers.charges, ax <span class="op">=</span> ax1)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Insurance cost (USD)'</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'Insurance Cost Boxplot for Smokers'</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co">#histogram</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>sns.histplot(df_smokers.charges, bins <span class="op">=</span> <span class="dv">40</span>, ax <span class="op">=</span> ax2)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">'Insurance Cost Distribution for Smokers'</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'smoker_charges_boxplot_histogram.png'</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>plt.clf()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-5-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 432x288 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="insurance-cost-statistics-for-smokers" class="level3">
<h3 class="anchored" data-anchor-id="insurance-cost-statistics-for-smokers">Insurance Cost Statistics for Smokers</h3>
<p>Summary Stats: - Mean: $32,050.23 - Median: $34,456.35 - Max: $63,770.43 - Min: $12,829.46 - Standard Deviation: $11,520.47 - Variance: 132721153.14</p>
<p>Given the distribution, we can say that the mean represents the true average insurance cost for smokers.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#find mean of insurance cost for smokers</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>smoker_mean <span class="op">=</span> <span class="bu">round</span>(np.mean(df_smokers.charges), <span class="dv">2</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The average insurance cost for being a smoker: $</span><span class="sc">{mean}</span><span class="st">'</span>.<span class="bu">format</span>(mean <span class="op">=</span> smoker_mean))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#find median of insurance cost for smokers</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>smoker_median <span class="op">=</span> <span class="bu">round</span>(np.median(df_smokers.charges), <span class="dv">2</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The median insurance cost for being a smoker: $</span><span class="sc">{median}</span><span class="st">'</span>.<span class="bu">format</span>(median <span class="op">=</span> smoker_median))</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co">#find standard deviation...</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>smoker_std <span class="op">=</span> <span class="bu">round</span>(np.std(df_smokers.charges),<span class="dv">2</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The standard deviation is: $</span><span class="sc">{std}</span><span class="st">'</span>.<span class="bu">format</span>(std <span class="op">=</span> smoker_std))</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co">#let's see the variance</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>smoker_var <span class="op">=</span> <span class="bu">round</span>(np.var(df_smokers.charges),<span class="dv">2</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The variance is: </span><span class="sc">{var}</span><span class="st">'</span>.<span class="bu">format</span>(var <span class="op">=</span> smoker_var))</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co">#maximum cost</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>smoker_max <span class="op">=</span> <span class="bu">round</span>(np.<span class="bu">max</span>(df_smokers.charges), <span class="dv">2</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The maximum insurance cost for being a smoker is: $</span><span class="sc">{max}</span><span class="st">'</span>.<span class="bu">format</span>(<span class="bu">max</span> <span class="op">=</span> smoker_max))</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co">#minimum cost</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>smoker_min <span class="op">=</span> <span class="bu">round</span>(np.<span class="bu">min</span>(df_smokers.charges), <span class="dv">2</span>)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The minimum insurance cost for being a smoker is: $</span><span class="sc">{min}</span><span class="st">'</span>.<span class="bu">format</span>(<span class="bu">min</span> <span class="op">=</span> smoker_min))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The average insurance cost for being a smoker: $32050.23
The median insurance cost for being a smoker: $34456.35
The standard deviation is: $11520.47
The variance is: 132721153.14
The maximum insurance cost for being a smoker is: $63770.43
The minimum insurance cost for being a smoker is: $12829.46</code></pre>
</div>
</div>
</section>
<section id="seperating-male-and-female-smokers" class="level3">
<h3 class="anchored" data-anchor-id="seperating-male-and-female-smokers">Seperating Male and Female Smokers</h3>
<p>I chose to seperate male and female smokers to see if there was a noticable difference in cost. Notice in the graphs below, that we can easily identify the culprit for the bimodal distribution. The <strong>BMI</strong> drastically influences the insurance cost when it is greater than or equal to 30 (the obese rating starts at 30 forward). <em>This means that being obese AND being a smoker can sharply increase your medical insurance cost.</em></p>
<p>Note: As <strong>Age</strong> slowly increases, the insurance cost also slowly increases. So, there is a gradual increase in insurance cost as you age. That is common sense since as one ages, one develops more health issues as they near death.</p>
</section>
<section id="analyzing-male-smokers" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-male-smokers">Analyzing Male Smokers</h3>
<p>Graph One: Cost Distribution - Bimodal Distribution is again present. - Two clusters of cost are due to an underlying variable.</p>
<p>Graph Two: Barplot of Average Cost per Child - No clear trend. - Only valuable note is that having 4 children seems to have an overall lower average insurance cost.</p>
<p>Graph Three: Scatterplot of Cost vs BMI with Region - There is a visable linear relationship between BMI and Cost. - There are two clusters of individuals but follows the linear relationship. - At &gt;=30 BMI, there is a clear signifcant increase in insurance cost for male smokers. - Note: a BMI of 30 or implies that the individual is “obese” (though, BMI is not necessarily a good measurement–see results). - No trends with the region.</p>
<p>Graph Four: Scatterplot of Cost vs Age with Children - There is a linear trend, but split into two linear clusters. - As found earlier, this is most likely due to BMI differences in the indivduals. - Overtime, an individual’s insurance cost will increase as expected.</p>
<p>Graph Five: Barplot of Average Cost per Region - No valuable insights can be drawn.</p>
<p>Graph Six: Boxplot of Male Smoker Insurance Cost - Noteworthy to see the spread of male smokers’ insurance cost.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#seperate all male smokers from the main data set</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>df_male_smoker <span class="op">=</span> df_smokers[df_smokers.sex <span class="op">==</span> <span class="st">'male'</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_male_smoker.head())</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">2</span>,<span class="dv">3</span>,figsize<span class="op">=</span>(<span class="dv">40</span>,<span class="dv">30</span>))</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">'darkgrid'</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(font_scale <span class="op">=</span> <span class="dv">3</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co">#histogram male smoker</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>sns.histplot(df_male_smoker.charges, bins <span class="op">=</span> <span class="dv">40</span>, ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">0</span>])</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_title(<span class="st">'Male Smoker Insurance Cost Distribution'</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_xlabel(<span class="st">'Insurnance Cost (USD)'</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co">#barplot for insurance cost of male smokers per child</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>df_children <span class="op">=</span> df_male_smoker.groupby(<span class="st">'children'</span>).mean().reset_index()</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_children.head())</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_children.children, y <span class="op">=</span> df_children.charges, ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">1</span>])</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_title(<span class="st">'Average Male Smoker Insurance Cost Per Child'</span>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Number of Children'</span>)</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="co">#scatterplot for insurance cost of male smokers by BMI</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_male_smoker.bmi, y <span class="op">=</span> df_male_smoker.charges,</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_male_smoker.region,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_male_smoker.region,</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>                sizes <span class="op">=</span> (<span class="dv">75</span>, <span class="dv">250</span>), ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">2</span>])</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].axvline(x <span class="op">=</span> <span class="dv">30</span>, color <span class="op">=</span> <span class="st">'gray'</span>, label <span class="op">=</span> <span class="st">'Obese BMI'</span>)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_title(<span class="st">'Male Smoker Insurance Cost vs BMI'</span>)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_xlabel(<span class="st">'BMI'</span>)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].legend(bbox_to_anchor <span class="op">=</span> (<span class="fl">1.0</span>, <span class="dv">1</span>))</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a><span class="co">#scatterplot for insurance cost of male smokers by age</span></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_male_smoker.age, y <span class="op">=</span> df_male_smoker.charges,</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_male_smoker.children,</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_male_smoker.children, sizes <span class="op">=</span> (<span class="dv">125</span>,<span class="dv">250</span>),</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>                ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">0</span>])</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_title(<span class="st">'Male Smoker Insurance Cost vs Age'</span>)</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_xlabel(<span class="st">'Age'</span>)</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a><span class="co">#barplot for insurance cost of male smokers per region</span></span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>df_region <span class="op">=</span> df_male_smoker.groupby(<span class="st">'region'</span>).mean().reset_index()</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_region.head())</span></span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_region.region,  y <span class="op">=</span> df_region.charges, ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">1</span>])</span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_title(<span class="st">'Average Male Smoker Insurance Cost Per Region'</span>)</span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Region'</span>)</span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a><span class="co">#boxplot of male smoker boxplot</span></span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x <span class="op">=</span> df_male_smoker.charges, ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">2</span>])</span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].set_title(<span class="st">'Male Smoker Insurance Cost Boxplot'</span>)</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].set_xlabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'male_smoker_charges_plots.png'</span>)</span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a>plt.clf()</span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-7-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 432x288 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="bmi-graph-highlighted" class="level3">
<h3 class="anchored" data-anchor-id="bmi-graph-highlighted">BMI Graph Highlighted</h3>
<p>As mentioned above, the reason why the cost distribution had two clusters was due to the difference in BMI in each male smoker. Male smokers with a BMI &gt;= 30 will that their expense increase by approximately 47%.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#highlight BMI graph</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize <span class="op">=</span> (<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_male_smoker.bmi, y <span class="op">=</span> df_male_smoker.charges,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_male_smoker.region,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_male_smoker.region,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                sizes <span class="op">=</span> (<span class="dv">75</span>, <span class="dv">250</span>))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>plt.axvline(x <span class="op">=</span> <span class="dv">30</span>, color <span class="op">=</span> <span class="st">'gray'</span>, label <span class="op">=</span> <span class="st">'Obese BMI'</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Male Smoker Insurance Cost vs BMI'</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'BMI'</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>plt.legend(bbox_to_anchor <span class="op">=</span> (<span class="fl">1.0</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>&lt;matplotlib.legend.Legend at 0x7fc2f6434670&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-8-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#analyze BMI &lt; 30</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>male_df_bmi <span class="op">=</span> df_male_smoker[df_male_smoker.bmi <span class="op">&lt;</span> <span class="dv">30</span>]</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>male_avg_cost <span class="op">=</span> <span class="bu">round</span>(np.mean(male_df_bmi.charges, axis <span class="op">=</span> <span class="dv">0</span>),<span class="dv">2</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average insurance cost for male smokers with a BMI of less than 30 equates to: $</span><span class="sc">{charge}</span><span class="st">"</span>.<span class="bu">format</span>(charge <span class="op">=</span> male_avg_cost))</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#analyze BMI &gt;= 30</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>male_df2_bmi <span class="op">=</span> df_male_smoker[df_male_smoker.bmi <span class="op">&gt;=</span> <span class="dv">30</span>]</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>male_avg_cost_2 <span class="op">=</span> <span class="bu">round</span>(np.mean(male_df2_bmi.charges, axis <span class="op">=</span> <span class="dv">0</span>),<span class="dv">2</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average insurance cost for male smokers with a BMI of greater than or equal to 30 equates to: $</span><span class="sc">{charge}</span><span class="st">"</span>.<span class="bu">format</span>(charge <span class="op">=</span> male_avg_cost_2))</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Difference of Insurance Cost</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>male_diff_cost <span class="op">=</span> male_avg_cost_2 <span class="op">-</span> male_avg_cost</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The difference in insurance cost from being at or over 30 BMI compared to being under 30 BMI for males is: $</span><span class="sc">{diff}</span><span class="st">"</span>.<span class="bu">format</span>(diff <span class="op">=</span> male_diff_cost))</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>male_diff_cost_percent <span class="op">=</span> <span class="dv">100</span><span class="op">*</span><span class="bu">round</span>(male_diff_cost <span class="op">/</span> male_avg_cost_2, <span class="dv">2</span>)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'A male smoker will suffer an increase of </span><span class="sc">{percent}% i</span><span class="st">n their insurance cost by being obese (BMI &gt;= 30)'</span>.<span class="bu">format</span>(percent <span class="op">=</span> male_diff_cost_percent))</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The average insurance cost for male smokers with a BMI of less than 30 equates to: $21643.07
The average insurance cost for male smokers with a BMI of greater than or equal to 30 equates to: $41131.57
The difference in insurance cost from being at or over 30 BMI compared to being under 30 BMI for males is: $19488.5
A male smoker will suffer an increase of 47.0% in their insurance cost by being obese (BMI &gt;= 30)</code></pre>
</div>
</div>
</section>
<section id="analyzing-female-smokers" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-female-smokers">Analyzing Female Smokers</h3>
<p>Graph One: Cost Distribution - Bimodal Distribution is again present. - Two clusters of cost are due to an underlying variable.</p>
<p>Graph Two: Barplot of Average Cost per Child - No clear trend. - Only valuable note is that having 5 children seems to have an overall lower average insurance cost.</p>
<p>Graph Three: Scatterplot of Cost vs BMI with Region - There is a visable linear relationship between BMI and Cost - There are two clusters of individuals but follows the linear relationship. - At &gt;=30 BMI, there is a clear signifcant increase in insurance cost for female smokers. - Note: a BMI of 30 or implies that the individual is “obese” (though, BMI is not necessarily a good measurement–see results). - No trends with the region.</p>
<p>Graph Four: Scatterplot of Cost vs Age with Children - There is a linear trend, but split into two linear clusters. - As found earlier, this is most likely due to BMI differences in the indivduals. - Overtime, an individual’s insurance cost will increase as expected.</p>
<p>Graph Five: Barplot of Average Cost per Region - No valuable insights can be drawn.</p>
<p>Graph Six: Boxplot of Female Smoker Insurance Cost - Noteworthy to see the spread of female smokers’ insurance cost.</p>
<p>Given that the Insurane Cost vs BMI is essentially the same as male smokers, the stated results will apply here.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#seperate all female smokers from the main data set</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>df_female_smoker <span class="op">=</span> df_smokers[df_smokers.sex <span class="op">==</span> <span class="st">'female'</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">2</span>,<span class="dv">3</span>,figsize<span class="op">=</span>(<span class="dv">40</span>,<span class="dv">30</span>))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">'darkgrid'</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(font_scale <span class="op">=</span> <span class="dv">2</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co">#histogram male smoker</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>sns.histplot(df_female_smoker.charges, bins <span class="op">=</span> <span class="dv">40</span>, ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">0</span>])</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_title(<span class="st">'Female Smoker Insurance Cost Distribution'</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_xlabel(<span class="st">'Insurnance Cost (USD)'</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co">#barplot for insurance cost of female smokers per child</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>df_children <span class="op">=</span> df_female_smoker.groupby(<span class="st">'children'</span>).mean().reset_index()</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_children.head())</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_children.children, y <span class="op">=</span> df_children.charges, ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">1</span>])</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_title(<span class="st">'Average Female Smoker Insurance Cost Per Child'</span>)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Number of Children'</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="co">#scatterplot for insurance cost of female smokers by BMI</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_female_smoker.bmi, y <span class="op">=</span> df_female_smoker.charges,</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_female_smoker.region,</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_female_smoker.region,</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>                sizes <span class="op">=</span> (<span class="dv">75</span>, <span class="dv">250</span>), ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">2</span>])</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].axvline(x <span class="op">=</span> <span class="dv">30</span>, color <span class="op">=</span> <span class="st">'gray'</span>, label <span class="op">=</span> <span class="st">'Obese BMI'</span>)</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_title(<span class="st">'Female Smoker Insurance Cost vs BMI'</span>)</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_xlabel(<span class="st">'BMI'</span>)</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].legend(bbox_to_anchor <span class="op">=</span> (<span class="fl">1.0</span>, <span class="dv">1</span>))</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a><span class="co">#scatterplot for insurance cost of female smokers by age</span></span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_female_smoker.age, y <span class="op">=</span> df_female_smoker.charges,</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_female_smoker.children,</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_female_smoker.children,</span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>                sizes <span class="op">=</span> (<span class="dv">125</span>, <span class="dv">250</span>), ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">0</span>])</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_title(<span class="st">'Female Smoker Insurance Cost vs Age'</span>)</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_xlabel(<span class="st">'Age'</span>)</span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a><span class="co">#barplot for insurance cost of female smokers per region</span></span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a>df_region <span class="op">=</span> df_female_smoker.groupby(<span class="st">'region'</span>).mean().reset_index()</span>
<span id="cb16-44"><a href="#cb16-44" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_region.head())</span></span>
<span id="cb16-45"><a href="#cb16-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-46"><a href="#cb16-46" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_region.region,  y <span class="op">=</span> df_region.charges, ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">1</span>])</span>
<span id="cb16-47"><a href="#cb16-47" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_title(<span class="st">'Average. Female Smoker Insurance Cost Per Region'</span>)</span>
<span id="cb16-48"><a href="#cb16-48" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Region'</span>)</span>
<span id="cb16-49"><a href="#cb16-49" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb16-50"><a href="#cb16-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-51"><a href="#cb16-51" aria-hidden="true" tabindex="-1"></a><span class="co">#boxplot of female smoker age vs bmi</span></span>
<span id="cb16-52"><a href="#cb16-52" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x <span class="op">=</span> df_female_smoker.charges, ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">2</span>])</span>
<span id="cb16-53"><a href="#cb16-53" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].set_title(<span class="st">'Female Smoker Insurance Cost Boxplot'</span>)</span>
<span id="cb16-54"><a href="#cb16-54" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].set_xlabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb16-55"><a href="#cb16-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-56"><a href="#cb16-56" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'female_smoker_charges_plots.png'</span>)</span>
<span id="cb16-57"><a href="#cb16-57" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb16-58"><a href="#cb16-58" aria-hidden="true" tabindex="-1"></a>plt.clf()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-10-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 432x288 with 0 Axes&gt;</code></pre>
</div>
</div>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#analyze BMI &lt; 30</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>female_df_bmi <span class="op">=</span> df_female_smoker[df_female_smoker.bmi <span class="op">&lt;</span> <span class="dv">30</span>]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>female_avg_cost <span class="op">=</span> <span class="bu">round</span>(np.mean(female_df_bmi.charges, axis <span class="op">=</span> <span class="dv">0</span>),<span class="dv">2</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average insurance cost for female smokers with a BMI of less than 30 equates to: $</span><span class="sc">{charge}</span><span class="st">"</span>.<span class="bu">format</span>(charge <span class="op">=</span> female_avg_cost))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co">#analyze BMI &gt;= 30</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>female_df2_bmi <span class="op">=</span> df_female_smoker[df_female_smoker.bmi <span class="op">&gt;=</span> <span class="dv">30</span>]</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>female_avg_cost_2 <span class="op">=</span> <span class="bu">round</span>(np.mean(female_df2_bmi.charges, axis <span class="op">=</span> <span class="dv">0</span>),<span class="dv">2</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average insurance cost for female smokers with a BMI of greater than or equal to 30 equates to: $</span><span class="sc">{charge}</span><span class="st">"</span>.<span class="bu">format</span>(charge <span class="op">=</span> female_avg_cost_2))</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Difference of Insurance Cost</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>female_diff_cost <span class="op">=</span> female_avg_cost_2 <span class="op">-</span> female_avg_cost</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The difference in cost from being at or over 30 BMI compared to being under 30 BMI for females is: $</span><span class="sc">{diff}</span><span class="st">"</span>.<span class="bu">format</span>(diff <span class="op">=</span> female_diff_cost))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The average insurance cost for female smokers with a BMI of less than 30 equates to: $21070.04
The average insurance cost for female smokers with a BMI of greater than or equal to 30 equates to: $42320.62
The difference in cost from being at or over 30 BMI compared to being under 30 BMI for females is: $21250.58</code></pre>
</div>
</div>
</section>
<section id="average-insurance-cost-comparision-of-male-and-female-smokers" class="level3">
<h3 class="anchored" data-anchor-id="average-insurance-cost-comparision-of-male-and-female-smokers">Average Insurance Cost Comparision of Male and Female Smokers</h3>
<p>Noteworthy mention: - Male smokers pay approximately 1.34% more than their female counterparts when their BMI less than 30. - Male smokers pay approximately 1.42% less than their female counterparts when their BMI greater than or equal to 30.</p>
<div class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot average insurance cost for male and female </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>df_bmi_less_than_30 <span class="op">=</span> df_smokers[df_smokers.bmi <span class="op">&lt;</span> <span class="dv">30</span>]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>df_one <span class="op">=</span> df_bmi_less_than_30.groupby(<span class="st">'sex'</span>).mean().reset_index()</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Get value</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>male_bmi_less_than_30 <span class="op">=</span> df_one[df_one.sex <span class="op">==</span> <span class="st">'male'</span>].charges.<span class="bu">sum</span>()</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>female_bmi_less_than_30 <span class="op">=</span> df_one[df_one.sex <span class="op">==</span> <span class="st">'female'</span>].charges.<span class="bu">sum</span>()</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co">#print value</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>male_female_sum <span class="op">=</span> male_bmi_less_than_30 <span class="op">+</span> female_bmi_less_than_30</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>por_male_less_30 <span class="op">=</span> male_bmi_less_than_30 <span class="op">/</span> male_female_sum</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>por_female_less_30 <span class="op">=</span> female_bmi_less_than_30 <span class="op">/</span> male_female_sum</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>diff_por <span class="op">=</span> <span class="bu">round</span>((por_male_less_30 <span class="op">-</span> por_female_less_30), <span class="dv">4</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Male smokers are expected to pay approximately </span><span class="sc">{diff_por}</span><span class="st">% more than their female counterparts when their BMI &lt; 30 "</span>.<span class="bu">format</span>(diff_por <span class="op">=</span> diff_por))</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>df_bmi_greater_than_or_equal_30 <span class="op">=</span> df_smokers[df_smokers.bmi <span class="op">&gt;=</span> <span class="dv">30</span>]</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>df_two <span class="op">=</span> df_bmi_greater_than_or_equal_30.groupby(<span class="st">'sex'</span>).mean().reset_index()</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>male_bmi_greq_30 <span class="op">=</span> df_two[df_two.sex <span class="op">==</span> <span class="st">'male'</span>].charges.<span class="bu">sum</span>()</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>female_bmi_greq_30 <span class="op">=</span> df_two[df_two.sex <span class="op">==</span> <span class="st">'female'</span>].charges.<span class="bu">sum</span>()</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>male_female_sum <span class="op">=</span> male_bmi_greq_30 <span class="op">+</span> female_bmi_greq_30</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>por_male_greq_30 <span class="op">=</span> male_bmi_greq_30 <span class="op">/</span> male_female_sum</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>por_female_greq_30 <span class="op">=</span> female_bmi_greq_30 <span class="op">/</span> male_female_sum</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>diff_por_greq <span class="op">=</span> <span class="bu">round</span>((por_male_greq_30 <span class="op">-</span> por_female_greq_30), <span class="dv">4</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>diff_por_greq <span class="op">=</span> <span class="bu">abs</span>(<span class="bu">round</span>(diff_por_greq, <span class="dv">4</span>))</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Male smokers are expected to pay approximately </span><span class="sc">{diff_por_greq}% le</span><span class="st">ss than their female counterparts when their BMI &gt;= 30"</span>.<span class="bu">format</span>(diff_por_greq <span class="op">=</span> diff_por_greq))</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_one)</span></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_two)</span></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a><span class="co">#df3 = pd.concat([df_one, df_two])</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df3)</span></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">2</span>,figsize<span class="op">=</span>(<span class="dv">25</span>,<span class="dv">10</span>))</span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">'darkgrid'</span>)</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(font_scale <span class="op">=</span> <span class="dv">2</span>)</span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a><span class="co">#BMI is less than 30</span></span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>sns.set_palette(<span class="st">'bright'</span>)</span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_one.sex, y <span class="op">=</span> df_one.charges, ax <span class="op">=</span> ax[<span class="dv">0</span>])</span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">'Sex'</span>)</span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">'Average Smoker Insurance Cost with BMI &lt; 30'</span>)</span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-49"><a href="#cb20-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-50"><a href="#cb20-50" aria-hidden="true" tabindex="-1"></a><span class="co">#BMI is greater than or equal to 30</span></span>
<span id="cb20-51"><a href="#cb20-51" aria-hidden="true" tabindex="-1"></a>sns.set_palette(<span class="st">'dark'</span>)</span>
<span id="cb20-52"><a href="#cb20-52" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_two.sex, y <span class="op">=</span> df_two.charges, ax <span class="op">=</span> ax[<span class="dv">1</span>])</span>
<span id="cb20-53"><a href="#cb20-53" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xlabel(<span class="st">'Sex'</span>)</span>
<span id="cb20-54"><a href="#cb20-54" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb20-55"><a href="#cb20-55" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">'Average Smoker Insurance Cost with BMI &gt;= 30'</span>)</span>
<span id="cb20-56"><a href="#cb20-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-57"><a href="#cb20-57" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'avg_insurance_cost_per_sex'</span>)</span>
<span id="cb20-58"><a href="#cb20-58" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb20-59"><a href="#cb20-59" aria-hidden="true" tabindex="-1"></a>plt.clf</span>
<span id="cb20-60"><a href="#cb20-60" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Male smokers are expected to pay approximately 1.34% more than their female counterparts when their BMI &lt; 30 
Male smokers are expected to pay approximately 1.42% less than their female counterparts when their BMI &gt;= 30</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-12-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display" data-execution_count="57">
<pre><code>&lt;function matplotlib.pyplot.clf()&gt;</code></pre>
</div>
</div>
</section>
<section id="boxplot-and-histogram-distribution-of-insurance-costs-for-nonsmokers" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-and-histogram-distribution-of-insurance-costs-for-nonsmokers">Boxplot and Histogram Distribution of Insurance Costs for Nonsmokers</h3>
<p>The interquartile range is $7,378.07. Spread is minimal from the first and third interquartiles.</p>
<p>Now, notice that we have a right-skewed distribution.</p>
<p>What could cause this? - Region? - Bmi? - Sex? - Children? - Age?</p>
<p>Keep in mind, there is a chance that we may not be able to determine the cause of those outliers.</p>
<div class="cell" data-execution_count="62">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>IQR <span class="op">=</span> stats.iqr(df_nonsmokers.charges, interpolation <span class="op">=</span> <span class="st">'midpoint'</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>IQR <span class="op">=</span> <span class="bu">round</span>(IQR, <span class="dv">2</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(IQR)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">2</span>,figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">10</span>))</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co">#boxplot</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>sns.boxplot(y <span class="op">=</span> df_nonsmokers.charges, ax <span class="op">=</span> ax1)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Insurance cost (USD)'</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'Insurance Cost Boxplot for Nonsmokers'</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co">#histogram</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>sns.histplot(df_nonsmokers.charges, bins <span class="op">=</span> <span class="dv">40</span>, ax <span class="op">=</span> ax2)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">'Insurance Cost Distribution for Nonsmokers'</span>)</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'nonsmoker_charges_boxplot_histogram.png'</span>)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>plt.clf()</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="co">#right skewed distribution...explain potential causes:  Male and Female? BMI?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>7378.07</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-13-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 432x288 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="analyzing-the-insurance-cost-of-nonsmokers" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-the-insurance-cost-of-nonsmokers">Analyzing the insurance cost of nonsmokers</h2>
<p>Now let’s look at the nonsmokers.</p>
<p>Summary Stats: - Mean: $8,434.27 - Median: $7,345.41 - Max: $39,910.61 - Min: $1,121.87 - Standard Deviation: $5,990.96 - Variance: 35891656</p>
<div class="cell" data-execution_count="58">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>df_nonsmokers <span class="op">=</span> df[df.smoker <span class="op">==</span> <span class="st">'no'</span>]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_nonsmokers.head())</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co">#find mean of insurance cost for nonsmokers</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>nonsmoker_mean <span class="op">=</span> <span class="bu">round</span>(np.mean(df_nonsmokers.charges), <span class="dv">2</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The nonsmoker average insurance cost for being a smoker: $</span><span class="sc">{mean}</span><span class="st">'</span>.<span class="bu">format</span>(mean <span class="op">=</span> nonsmoker_mean))</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co">#find median of insurance cost for nonsmokers</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>nonsmoker_median <span class="op">=</span> <span class="bu">round</span>(np.median(df_nonsmokers.charges), <span class="dv">2</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The nonsmoker median insurance cost for being a smoker: $</span><span class="sc">{median}</span><span class="st">'</span>.<span class="bu">format</span>(median <span class="op">=</span> nonsmoker_median))</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co">#find standard deviation...</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>nonsmoker_std <span class="op">=</span> <span class="bu">round</span>(np.std(df_nonsmokers.charges),<span class="dv">2</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The nonsmoker standard deviation is: $</span><span class="sc">{std}</span><span class="st">'</span>.<span class="bu">format</span>(std <span class="op">=</span> nonsmoker_std))</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="co">#let's see the variance</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>nonsmoker_var <span class="op">=</span> <span class="bu">round</span>(np.var(df_nonsmokers.charges),<span class="dv">2</span>)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The nonsmoker variance is: </span><span class="sc">{var}</span><span class="st">'</span>.<span class="bu">format</span>(var <span class="op">=</span> nonsmoker_var))</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co">#maximum cost</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>nonsmoker_max <span class="op">=</span> <span class="bu">round</span>(np.<span class="bu">max</span>(df_nonsmokers.charges), <span class="dv">2</span>)</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The nonsmoker maximum insurance cost is: $</span><span class="sc">{max}</span><span class="st">'</span>.<span class="bu">format</span>(<span class="bu">max</span> <span class="op">=</span> nonsmoker_max))</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="co">#minimum cost</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>nonsmoker_min <span class="op">=</span> <span class="bu">round</span>(np.<span class="bu">min</span>(df_nonsmokers.charges), <span class="dv">2</span>)</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The nonsmoker minimum insurance cost is: $</span><span class="sc">{min}</span><span class="st">'</span>.<span class="bu">format</span>(<span class="bu">min</span> <span class="op">=</span> nonsmoker_min))</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="co">#For explaination a high standard deviation tells us that here are other reasons the cost is so high since it varies signifcantly</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The nonsmoker average insurance cost for being a smoker: $8434.27
The nonsmoker median insurance cost for being a smoker: $7345.41
The nonsmoker standard deviation is: $5990.96
The nonsmoker variance is: 35891656.0
The nonsmoker maximum insurance cost is: $36910.61
The nonsmoker minimum insurance cost is: $1121.87</code></pre>
</div>
</div>
<section id="analyzing-male-nonsmokers" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-male-nonsmokers">Analyzing Male Nonsmokers</h3>
<p>Graph One: Cost Distribution - Right-skewed distribution is again present. - Knowing this, we should go with the median as the most appropriate statistic instead of the mean.</p>
<p>Graph Two: Barplot of Average Cost per Child - There seems to be a trend that having more children will lead to higher average insurance costs. - Given the information from the smokers, when an individual has 5 children or more, their insurance costs drops signifcantly. - However, the lowest average comes from having no children at all.</p>
<p>Graph Three: Scatterplot of Cost vs BMI with Region - There is no correlation between cost and BMI of nonsmokers. - This is an interesting finding. - No trends with the region.</p>
<p>Graph Four: Scatterplot of Cost vs Age with Children - Strong linear relationship between insurance cost and age. - A secondary trend is shown with the number of children. - The less children, the insurance cost is on the lower end of the linear relationship. - The more children, the insurance cost is on the higher end of the linear relationship - The outliers do not follow the trend line.</p>
<p>Graph Five: Barplot of Average Cost per Region - No valuable insights can be drawn. - Some regions are simply cheaper than others.</p>
<p>Graph Six: Boxplot of Male Smoker Insurance Cost - Noteworthy to see the spread of male smokers’ insurance cost.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#seperate all male nonsmokers from the main data set</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>df_male_nonsmoker <span class="op">=</span> df_nonsmokers[df_nonsmokers.sex <span class="op">==</span> <span class="st">'male'</span>]</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co">#print(male_nonsmoker.head())</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">2</span>,<span class="dv">3</span>,figsize<span class="op">=</span>(<span class="dv">40</span>,<span class="dv">30</span>))</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">'darkgrid'</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(font_scale <span class="op">=</span> <span class="dv">2</span>)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co">#histogram male nonsmoker</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>sns.histplot(df_male_nonsmoker.charges, bins <span class="op">=</span> <span class="dv">40</span>, ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">0</span>])</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_title(<span class="st">'Male Nonsmoker Insurance Cost Distribution'</span>)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_xlabel(<span class="st">'Insurnance Cost (USD)'</span>)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co">#barplot for insurance cost of male nonsmokers per child</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>df_children <span class="op">=</span> df_male_nonsmoker.groupby(<span class="st">'children'</span>).mean().reset_index()</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_children.children, y <span class="op">=</span> df_children.charges, ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">1</span>])</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_title(<span class="st">'Average Male Nonsmoker Insurance Cost Per Child'</span>)</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Number of Children'</span>)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="co">#scatterplot for insurance cost of male nonsmokers by BMI</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_male_nonsmoker.bmi, y <span class="op">=</span> df_male_nonsmoker.charges,</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_male_nonsmoker.region,</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_male_nonsmoker.region,</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>                sizes <span class="op">=</span> (<span class="dv">75</span>, <span class="dv">250</span>), ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">2</span>])</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].axvline(x <span class="op">=</span> <span class="dv">30</span>, color <span class="op">=</span> <span class="st">'gray'</span>, label <span class="op">=</span> <span class="st">'Obese BMI'</span>)</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_title(<span class="st">'Male Nonsmoker Insurance Cost vs BMI'</span>)</span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_xlabel(<span class="st">'BMI'</span>)</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].legend(bbox_to_anchor <span class="op">=</span> (<span class="fl">1.0</span>, <span class="dv">1</span>))</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a><span class="co">#scatterplot for insurance cost of male nonsmokers by age</span></span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_male_nonsmoker.age, y <span class="op">=</span> df_male_nonsmoker.charges,</span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_male_nonsmoker.children,</span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_male_nonsmoker.children, sizes <span class="op">=</span> (<span class="dv">125</span>,<span class="dv">250</span>),</span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a>                ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">0</span>])</span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_title(<span class="st">'Male Nonsmoker Insurance Cost vs Age'</span>)</span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_xlabel(<span class="st">'Age'</span>)</span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a><span class="co">#barplot for insurance cost of male nonsmokers per region</span></span>
<span id="cb28-43"><a href="#cb28-43" aria-hidden="true" tabindex="-1"></a>df_region <span class="op">=</span> df_male_nonsmoker.groupby(<span class="st">'region'</span>).mean().reset_index()</span>
<span id="cb28-44"><a href="#cb28-44" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_region.region,  y <span class="op">=</span> df_region.charges, ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">1</span>])</span>
<span id="cb28-45"><a href="#cb28-45" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_title(<span class="st">'Average Male Nonsmoker Insurance Cost Per Region'</span>)</span>
<span id="cb28-46"><a href="#cb28-46" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Region'</span>)</span>
<span id="cb28-47"><a href="#cb28-47" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb28-48"><a href="#cb28-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-49"><a href="#cb28-49" aria-hidden="true" tabindex="-1"></a><span class="co">#boxplot of male nonsmoker boxplot</span></span>
<span id="cb28-50"><a href="#cb28-50" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x <span class="op">=</span> df_male_nonsmoker.charges, ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">2</span>])</span>
<span id="cb28-51"><a href="#cb28-51" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].set_title(<span class="st">'Male Nonsmoker Insurance Cost Boxplot'</span>)</span>
<span id="cb28-52"><a href="#cb28-52" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].set_xlabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb28-53"><a href="#cb28-53" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'male_nonsmoker_charges_plots.png'</span>)</span>
<span id="cb28-54"><a href="#cb28-54" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb28-55"><a href="#cb28-55" aria-hidden="true" tabindex="-1"></a>plt.clf()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-15-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 432x288 with 0 Axes&gt;</code></pre>
</div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#highlight scatter plot for linear trend</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize <span class="op">=</span> (<span class="dv">15</span>, <span class="dv">10</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_male_nonsmoker.age, y <span class="op">=</span> df_male_nonsmoker.charges,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_male_nonsmoker.children,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_male_nonsmoker.children,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                sizes <span class="op">=</span> (<span class="dv">75</span>, <span class="dv">200</span>))</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Male Nonsmoker Insurance Cost vs Age'</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Age'</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'male_nonsmoker_insurance_cost_vs_age.png'</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>plt.clf()</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="co">#highlight this</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="co">#solid evidence that as age increases, your insurance cost increases as well.</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="co">#people with more children see a slightly higher cost overall </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-16-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 432x288 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="analyzing-female-nonsmokers" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-female-nonsmokers">Analyzing Female Nonsmokers</h3>
<p>Graph One: Cost Distribution - Right-skewed distribution is again present. - Knowing this, we should go with the median as the most appropriate statistic instead of the mean.</p>
<p>Graph Two: Barplot of Average Cost per Child - Similar to the male nonsmokers, there seems to be a trend that having more children will result in higher average insurance costs. - Given the information from the smokers, when an individual has 5 children or more, their insurance costs drops on average. - However, the lowest average comes from having no children at all.</p>
<p>Graph Three: Scatterplot of Cost vs BMI with Region - Again, there is no correlation between cost and BMI of nonsmokers. - No trends with the region.</p>
<p>Graph Four: Scatterplot of Cost vs Age with Children - Strong linear relationship between insurance cost and age. - A secondary trend is shown with the number of children. - The less children, the insurance cost is on the lower end of the linear relationship. - The more children, the insurance cost is on the higher end of the linear relationship - The outliers do not follow the trend line.</p>
<p>Graph Five: Barplot of Average Cost per Region - There is a slight trend of region importance. - The northeast is more expensive on average than the southwest.</p>
<p>Graph Six: Boxplot of Male Smoker Insurance Cost - Noteworthy to see the spread of male smokers’ insurance cost.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#seperate all female nonsmokers from the main data set</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>df_female_nonsmoker <span class="op">=</span> df_nonsmokers[df_nonsmokers.sex <span class="op">==</span> <span class="st">'female'</span>]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#print(df_female_nonsmoker.head())</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">2</span>,<span class="dv">3</span>,figsize<span class="op">=</span>(<span class="dv">40</span>,<span class="dv">30</span>))</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">'darkgrid'</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(font_scale <span class="op">=</span> <span class="dv">2</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co">#histogram Female nonsmoker</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>sns.histplot(df_female_nonsmoker.charges, bins <span class="op">=</span> <span class="dv">40</span>, ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">0</span>])</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_title(<span class="st">'Female Nonsmoker Insurance Cost Distribution'</span>)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_xlabel(<span class="st">'Insurnance Cost (USD)'</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co">#barplot for insurance cost of Female nonsmokers per child</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>df_children <span class="op">=</span> df_female_nonsmoker.groupby(<span class="st">'children'</span>).mean().reset_index()</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_children.children, y <span class="op">=</span> df_children.charges, ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">1</span>])</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_title(<span class="st">'Average Female Nonsmoker Insurance Cost Per Child'</span>)</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Number of Children'</span>)</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="co">#scatterplot for insurance cost of Female nonsmokers by BMI</span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_female_nonsmoker.bmi, y <span class="op">=</span> df_female_nonsmoker.charges,</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_female_nonsmoker.region,</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_female_nonsmoker.region,</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>                sizes <span class="op">=</span> (<span class="dv">75</span>, <span class="dv">250</span>), ax <span class="op">=</span> ax[<span class="dv">0</span>,<span class="dv">2</span>])</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].axvline(x <span class="op">=</span> <span class="dv">30</span>, color <span class="op">=</span> <span class="st">'gray'</span>, label <span class="op">=</span> <span class="st">'Obese BMI'</span>)</span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_title(<span class="st">'Female Nonsmoker Insurance Cost vs BMI'</span>)</span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_xlabel(<span class="st">'BMI'</span>)</span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].legend(bbox_to_anchor <span class="op">=</span> (<span class="fl">1.0</span>, <span class="dv">1</span>))</span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a><span class="co">#scatterplot for insurance cost of Female nonsmokers by age</span></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x <span class="op">=</span> df_female_nonsmoker.age, y <span class="op">=</span> df_female_nonsmoker.charges,</span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>                hue <span class="op">=</span> df_female_nonsmoker.children,</span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>                size <span class="op">=</span> df_female_nonsmoker.children, sizes <span class="op">=</span> (<span class="dv">125</span>,<span class="dv">250</span>),</span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>                ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">0</span>])</span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_title(<span class="st">'Female Nonsmoker Insurance Cost vs Age'</span>)</span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_xlabel(<span class="st">'Age'</span>)</span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_ylabel(<span class="st">'Insurance Costs (USD)'</span>)</span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a><span class="co">#barplot for insurance cost of Female nonsmokers per region</span></span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a>df_region <span class="op">=</span> df_female_nonsmoker.groupby(<span class="st">'region'</span>).mean().reset_index()</span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a>sns.barplot(x <span class="op">=</span> df_region.region,  y <span class="op">=</span> df_region.charges, ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">1</span>])</span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_title(<span class="st">'Average Female Nonsmoker Insurance Cost Per Region'</span>)</span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_xlabel(<span class="st">'Region'</span>)</span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_ylabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-49"><a href="#cb32-49" aria-hidden="true" tabindex="-1"></a><span class="co">#boxplot of Female nonsmoker boxplot</span></span>
<span id="cb32-50"><a href="#cb32-50" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x <span class="op">=</span> df_male_nonsmoker.charges, ax <span class="op">=</span> ax[<span class="dv">1</span>,<span class="dv">2</span>])</span>
<span id="cb32-51"><a href="#cb32-51" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].set_title(<span class="st">'Male Nonsmoker Insurance Cost Boxplot'</span>)</span>
<span id="cb32-52"><a href="#cb32-52" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].set_xlabel(<span class="st">'Insurance Cost (USD)'</span>)</span>
<span id="cb32-53"><a href="#cb32-53" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'female_nonsmoker_charges_plots.png'</span>)</span>
<span id="cb32-54"><a href="#cb32-54" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb32-55"><a href="#cb32-55" aria-hidden="true" tabindex="-1"></a>plt.clf()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="US_Medical_Insurance_Costs_v2_files/figure-html/cell-17-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 432x288 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="nonsmokers-vs-smokers" class="level1">
<h1>Nonsmokers vs Smokers</h1>
<div class="cell" data-execution_count="113">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nonsmokers</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>df_avg <span class="op">=</span> df_nonsmokers.groupby(<span class="st">'sex'</span>).mean().reset_index()</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>nonsmoker_male <span class="op">=</span>  <span class="bu">round</span>((df_avg[df_avg.sex <span class="op">==</span> <span class="st">'male'</span>].charges.<span class="bu">sum</span>()),<span class="dv">2</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>nonsmoker_female <span class="op">=</span> <span class="bu">round</span>((df_avg[df_avg.sex <span class="op">==</span> <span class="st">'female'</span>].charges.<span class="bu">sum</span>()),<span class="dv">2</span>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>diff <span class="op">=</span> <span class="bu">round</span>((nonsmoker_female <span class="op">-</span> nonsmoker_male), <span class="dv">2</span>)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> nonsmoker_male <span class="op">+</span> nonsmoker_female</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>nonsmoker_percent_diff <span class="op">=</span> <span class="bu">round</span>((((nonsmoker_female <span class="op">-</span> nonsmoker_male) <span class="op">/</span> total) <span class="op">*</span> <span class="dv">100</span>),<span class="dv">2</span>) </span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average insurance cost for a nonsmoker male is $</span><span class="sc">{avg}</span><span class="st">."</span>.<span class="bu">format</span>(avg <span class="op">=</span> nonsmoker_male))</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average insurance cost for a nonsmoker female is $</span><span class="sc">{avg}</span><span class="st">."</span>.<span class="bu">format</span>(avg <span class="op">=</span> nonsmoker_female))</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average difference in insurance cost for nonsmoker male and female is $</span><span class="sc">{diff}</span><span class="st">.</span><span class="ch">\n</span><span class="st">"</span>.<span class="bu">format</span>(diff <span class="op">=</span> diff))</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The nonsmoker males are charged </span><span class="sc">{percent}% le</span><span class="st">ss than their female counterpart.</span><span class="ch">\n</span><span class="st">"</span>.<span class="bu">format</span>(percent <span class="op">=</span> nonsmoker_percent_diff))</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Smokers</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>df_avg2 <span class="op">=</span> df_smokers.groupby(<span class="st">'sex'</span>).mean().reset_index()</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>smoker_male <span class="op">=</span>  <span class="bu">round</span>((df_avg2[df_avg2.sex <span class="op">==</span> <span class="st">'male'</span>].charges.<span class="bu">sum</span>()),<span class="dv">2</span>)</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>smoker_female <span class="op">=</span> <span class="bu">round</span>((df_avg2[df_avg2.sex <span class="op">==</span> <span class="st">'female'</span>].charges.<span class="bu">sum</span>()),<span class="dv">2</span>)</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>diff2 <span class="op">=</span> <span class="bu">round</span>((smoker_male <span class="op">-</span> smoker_female), <span class="dv">2</span>)</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> smoker_male <span class="op">+</span> smoker_female</span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>smoker_percent_diff <span class="op">=</span> <span class="bu">round</span>((((smoker_male <span class="op">-</span> smoker_female) <span class="op">/</span> total) <span class="op">*</span> <span class="dv">100</span>),<span class="dv">2</span>) </span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average insurance cost for a smoker male is $</span><span class="sc">{avg}</span><span class="st">."</span>.<span class="bu">format</span>(avg <span class="op">=</span> smoker_male))</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average insurance cost for a smoker female is $</span><span class="sc">{avg}</span><span class="st">."</span>.<span class="bu">format</span>(avg <span class="op">=</span> smoker_female))</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The average difference in insurance cost for smoker male and female is $</span><span class="sc">{diff}</span><span class="st">.</span><span class="ch">\n</span><span class="st">"</span>.<span class="bu">format</span>(diff <span class="op">=</span> diff2))</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The smoker males are charged </span><span class="sc">{percent}</span><span class="st">% more than their female counterpart.</span><span class="ch">\n</span><span class="st">"</span>.<span class="bu">format</span>(percent <span class="op">=</span> smoker_percent_diff))</span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a><span class="co">#Comparision</span></span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a>ins_cost_diff_male <span class="op">=</span> smoker_male <span class="op">-</span> nonsmoker_male</span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>ins_cost_diff_female <span class="op">=</span> smoker_female <span class="op">-</span> nonsmoker_female</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a>ins_cost_avg_diff <span class="op">=</span> diff2 <span class="op">-</span> diff</span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a>ins_cost_percent_male <span class="op">=</span> <span class="bu">round</span>((smoker_male <span class="op">/</span> nonsmoker_male) <span class="op">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a>ins_cost_percent_female <span class="op">=</span> <span class="bu">round</span>((smoker_female <span class="op">/</span> nonsmoker_female) <span class="op">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-43"><a href="#cb34-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-44"><a href="#cb34-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-45"><a href="#cb34-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"On average, a male nonsmoker pays $</span><span class="sc">{nonsmoker}</span><span class="st">, while a female smoker pays $</span><span class="sc">{smoker}</span><span class="st">."</span>.<span class="bu">format</span>(nonsmoker <span class="op">=</span> nonsmoker_male, smoker <span class="op">=</span> smoker_male))</span>
<span id="cb34-46"><a href="#cb34-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The difference in their insurance charges is $</span><span class="sc">{diff_male}</span><span class="st">."</span>.<span class="bu">format</span>(diff_male <span class="op">=</span> ins_cost_diff_male))</span>
<span id="cb34-47"><a href="#cb34-47" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"A male smoker will get charged approxmiately </span><span class="sc">{percent}</span><span class="st">% more than a nonsmoker.</span><span class="ch">\n</span><span class="st">"</span>.<span class="bu">format</span>(percent <span class="op">=</span> ins_cost_percent_male))</span>
<span id="cb34-48"><a href="#cb34-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-49"><a href="#cb34-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"On average, a female nonsmoker pays $</span><span class="sc">{nonsmoker}</span><span class="st">, while a female smoker pays $</span><span class="sc">{smoker}</span><span class="st">."</span>.<span class="bu">format</span>(nonsmoker <span class="op">=</span> nonsmoker_female, smoker <span class="op">=</span> smoker_female))</span>
<span id="cb34-50"><a href="#cb34-50" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The difference in their insurance charges is $</span><span class="sc">{diff_female}</span><span class="st">."</span>.<span class="bu">format</span>(diff_female <span class="op">=</span> ins_cost_diff_female))</span>
<span id="cb34-51"><a href="#cb34-51" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"A female smoker will get charged approxmiately </span><span class="sc">{percent}</span><span class="st">% more than a nonsmoker."</span>.<span class="bu">format</span>(percent <span class="op">=</span> ins_cost_percent_female))</span>
<span id="cb34-52"><a href="#cb34-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-53"><a href="#cb34-53" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The average insurance cost for a nonsmoker male is $8087.2.
The average insurance cost for a nonsmoker female is $8762.3.
The average difference in insurance cost for nonsmoker male and female is $675.1.

The nonsmoker males are charged 4.01% less than their female counterpart.

The average insurance cost for a smoker male is $33042.01.
The average insurance cost for a smoker female is $30679.0.
The average difference in insurance cost for smoker male and female is $2363.01.

The smoker males are charged 3.71% more than their female counterpart.

On average, a male nonsmoker pays $8087.2, while a female smoker pays $33042.01.
The difference in their insurance charges is $24954.81.
A male smoker will get charged approxmiately 408.57% more than a nonsmoker.

On average, a female nonsmoker pays $8762.3, while a female smoker pays $30679.0.
The difference in their insurance charges is $21916.7.
A female smoker will get charged approxmiately 350.12% more than a nonsmoker.</code></pre>
</div>
</div>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>It is clear that smoking will increase your health insurance charges. Male and female smokers will receive an additional charge for having a BMI equal or greater than 30. Male smokers hitch a 52% increase while female smokers endure a 49% increase. Keep in mind that this apart from their base premium increase for being smokers in the first place. To emphasize, male smokers will approximately be charged 408.57% more than their nonsmoker counterpart. Similarly, female smokers approximately pay 350.12% more than their nonsmoker counterparts. Given the data, it pushes the idea that smoking and being in an unhealthy body mass index will punish those individuals through higher health insurance charges. Note: Overtime, health insurance does get slightly more expensive as we age.</p>
<p>There is much more to be done with this project. I may come back to it and do some machine learning methods to predict if this sample represents the entire population or not.</p>
<p>I included two articles: One states that BMI metric is an inaccurate method to measure human height and weight; the other confirms that tabacco usage allows insurance companies to charge those individuals a premium.</p>
<p>“BMI (body mass index), which is based on the height and weight of a person, is an inaccurate measure of body fat content and does not take into account muscle mass, bone density, overall body composition, and racial and sex differences” (source: https://www.medicalnewstoday.com/articles/265215#:~:text=BMI%20(body%20mass%20index)%2C,of%20Medicine%2C%20University%20of%20Pennsylvania.)</p>
<p>“The practice of charging tobacco users more is called tobacco rating. The ACA allows for insurance companies to charge smokers up to 50% more (or premiums that are 1.5 times higher) than non-smokers through a tobacco surcharge.” (source: https://www.healthmarkets.com/content/smoking-and-health-insurance#:~:text=The%20Cost%20of%20Health%20Insurance%20for%20Smokers%20Vs.&amp;text=The%20practice%20of%20charging%20tobacco,smokers%20through%20a%20tobacco%20surcharge).</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>