project:
  type: website
  output-dir: docs
website:
  search:
    type: textbox 
  open-graph: true
  title: "Brian Cervantes Alvarez"
  navbar:
    right:
      - text: "About"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "Talks"
        file: talks.qmd
      - text: "Resources"
        file: resources.qmd
      
  page-footer:
    left:
      - href: https://www.quarto.org
        text: Made with quarto®
    right: 
      - href: license.qmd
        text: License
      - icon: linkedin
        href: https://www.linkedin.com/in/bcervantesalvarez/
      - icon: github
        href: https://github.com/bcervantesalvarez/
      - icon: envelope-fill
        href: mailto:briancervantesalvarez@gmail.com
format:
  html:
    citations-hover: true
    footnotes-hover: true
    theme: 
      - BCA_LightTheme.scss
editor: visual

