project:
  type: website
  output-dir: docs

website:
  open-graph: true
  title: "Brian Cervantes Alvarez"
  navbar:
    right:
      - text: "About Me"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Presentations"
        file: presentation.qmd
      - text: "Resume"
        file: resume.qmd
      
  page-footer:
    left:
      - href: https://www.quarto.org
        text: Made with quarto®
    right: 
      - href: license.qmd
        text: License
      - icon: linkedin
        href: https://www.linkedin.com/in/bcervantesalvarez/
      - icon: github
        href: https://github.com/bcervantesalvarez/
      - icon: envelope-fill
        href: mailto:briancervantesalvarez@gmail.com
format:
  html:
    citations-hover: true
    footnotes-hover: true
    theme: 
      light: BCA_LightTheme.scss
      dark: BCA_DarkTheme.scss

editor: visual

