project:
  type: website
  output-dir: docs

website:
  title: "Brian Cervantes Alvarez"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - resume.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: LinkedIn
format:
  html:
    theme: lux
    css: styles.css
    mainfont: Futura

editor: visual

