project:
  type: website
  output-dir: docs

website:
  title: "Brian Cervantes Alvarez"
  navbar:
    right:
      - text: "Portfolio"
        file: index.qmd
      - text: "Resume"
        file: resume.qmd
      - text: "About Me"
        file: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/bcervantesalvarez/
      - icon: github
        href: https://github.com/bcervantesalvarez/
      - icon: envelope-fill
        href: mailto:briancervantesalvarez@gmail.com
format:
  html:
    theme: 
      light: lux.scss
      dark: cyborg.scss
    css: styles.css
    fontsize: 0.9em
    linestretch: 2
    monofont: "Monaco"

editor: visual

