project:
  type: website
  output-dir: docs
website:
  favicon: Assets/Images/preview.png
  twitter-card: true
  site-url: https://datascienceyapper.com
  search:
    type: textbox 
  open-graph: true
  title: "Home"
  navbar:
    right:
      - text: "About"
        href: Content/About/index.qmd
      - text: "Projects"
        href: Content/Projects/index.qmd
      - text: "Blog"
        href: Content/Blog/index.qmd
      - text: "Talks"
        href: Content/Talks/index.qmd
      - text: "Resources"
        href: Content/Resources/index.qmd
  page-footer:
    left:
      - href: https://www.quarto.org
        text: Made with Quarto®
      - href: https://chatgpt.com/
        text: Built with ChatGPT®
      - href: https://www.cloudflare.com/
        text: Hosted with Cloudflare®
    right: 
      - href: Content/Privacy/index.qmd
        text: Privacy Policy
      - href: Content/License/index.qmd
        text: License
      - icon: linkedin
        href: https://www.linkedin.com/in/bcervantesalvarez/
      - icon: github
        href: https://github.com/bcervantesalvarez/
      - icon: envelope-fill
        href: mailto:briancervantesalvarez@gmail.com
format:
  html:
    citations-hover: true
    footnotes-hover: true
    theme: Assets/Themes/MainThemeBCA.scss
    highlight-style: github-dark
    include-after-body: Assets/HTML/Cookies/custom-cookie-consent.html
editor: source
