project:
  type: website
  output-dir: docs

website:
  title: "Brian Cervantes Alvarez"
  navbar:
    right:
      - text: "Portfolio"
        file: index.qmd
      - text: "Resume"
        file: resume.qmd
      - text: "About Me"
        file: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/bcervantesalvarez/
      - icon: github
        href: https://github.com/bcervantesalvarez/
      - icon: envelope
        href: mailto:briancervantesalvarez@gmail.com
format:
  html:
    theme: 
      light: lux
      dark: cyborg
    css: styles.css
    mainfont: Futura

editor: visual

