<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brian Cervantes Alvarez">
<meta name="dcterms.date" content="2022-07-14">

<title>Brian Cervantes Alvarez - U.S. Medical Insurance Costs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Brian Cervantes Alvarez</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html">
 <span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/bcervantesalvarez/"><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/bcervantesalvarez/"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:briancervantesalvarez@gmail.com"><i class="bi bi-envelope" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">U.S. Medical Insurance Costs</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">python</div>
                <div class="quarto-category">healthcare</div>
                <div class="quarto-category">analysis</div>
                <div class="quarto-category">stats</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Brian Cervantes Alvarez </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 14, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#u.s.-medical-insurance-costs" id="toc-u.s.-medical-insurance-costs" class="nav-link active" data-scroll-target="#u.s.-medical-insurance-costs">U.S. Medical Insurance Costs</a>
  <ul class="collapse">
  <li><a href="#purpose-of-this-project" id="toc-purpose-of-this-project" class="nav-link" data-scroll-target="#purpose-of-this-project">Purpose of this Project</a>
  <ul class="collapse">
  <li><a href="#set-up-and-importing-the-data" id="toc-set-up-and-importing-the-data" class="nav-link" data-scroll-target="#set-up-and-importing-the-data">Set Up and Importing the Data</a></li>
  </ul></li>
  <li><a href="#analyzing-smoker-insurance-costs" id="toc-analyzing-smoker-insurance-costs" class="nav-link" data-scroll-target="#analyzing-smoker-insurance-costs">Analyzing Smoker Insurance Costs</a>
  <ul class="collapse">
  <li><a href="#histogram-plot-of-smokers-vs-nonsmokers" id="toc-histogram-plot-of-smokers-vs-nonsmokers" class="nav-link" data-scroll-target="#histogram-plot-of-smokers-vs-nonsmokers">Histogram Plot of Smokers vs Nonsmokers</a></li>
  <li><a href="#boxplot-and-histogram-distribution-of-insurance-costs-for-smokers" id="toc-boxplot-and-histogram-distribution-of-insurance-costs-for-smokers" class="nav-link" data-scroll-target="#boxplot-and-histogram-distribution-of-insurance-costs-for-smokers">Boxplot and Histogram Distribution of Insurance Costs for Smokers</a></li>
  <li><a href="#insurance-cost-statistics-for-smokers" id="toc-insurance-cost-statistics-for-smokers" class="nav-link" data-scroll-target="#insurance-cost-statistics-for-smokers">Insurance Cost Statistics for Smokers</a></li>
  <li><a href="#seperating-male-and-female-smokers" id="toc-seperating-male-and-female-smokers" class="nav-link" data-scroll-target="#seperating-male-and-female-smokers">Seperating Male and Female Smokers</a></li>
  <li><a href="#analyzing-male-smokers" id="toc-analyzing-male-smokers" class="nav-link" data-scroll-target="#analyzing-male-smokers">Analyzing Male Smokers</a></li>
  <li><a href="#bmi-graph-highlighted" id="toc-bmi-graph-highlighted" class="nav-link" data-scroll-target="#bmi-graph-highlighted">BMI Graph Highlighted</a></li>
  <li><a href="#analyzing-female-smokers" id="toc-analyzing-female-smokers" class="nav-link" data-scroll-target="#analyzing-female-smokers">Analyzing Female Smokers</a></li>
  <li><a href="#average-insurance-cost-comparision-of-male-and-female-smokers" id="toc-average-insurance-cost-comparision-of-male-and-female-smokers" class="nav-link" data-scroll-target="#average-insurance-cost-comparision-of-male-and-female-smokers">Average Insurance Cost Comparision of Male and Female Smokers</a></li>
  <li><a href="#boxplot-and-histogram-distribution-of-insurance-costs-for-nonsmokers" id="toc-boxplot-and-histogram-distribution-of-insurance-costs-for-nonsmokers" class="nav-link" data-scroll-target="#boxplot-and-histogram-distribution-of-insurance-costs-for-nonsmokers">Boxplot and Histogram Distribution of Insurance Costs for Nonsmokers</a></li>
  </ul></li>
  <li><a href="#analyzing-the-insurance-cost-of-nonsmokers" id="toc-analyzing-the-insurance-cost-of-nonsmokers" class="nav-link" data-scroll-target="#analyzing-the-insurance-cost-of-nonsmokers">Analyzing the insurance cost of nonsmokers</a>
  <ul class="collapse">
  <li><a href="#analyzing-male-nonsmokers" id="toc-analyzing-male-nonsmokers" class="nav-link" data-scroll-target="#analyzing-male-nonsmokers">Analyzing Male Nonsmokers</a></li>
  <li><a href="#analyzing-female-nonsmokers" id="toc-analyzing-female-nonsmokers" class="nav-link" data-scroll-target="#analyzing-female-nonsmokers">Analyzing Female Nonsmokers</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#nonsmokers-vs-smokers" id="toc-nonsmokers-vs-smokers" class="nav-link" data-scroll-target="#nonsmokers-vs-smokers">Nonsmokers vs Smokers</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">




<section id="u.s.-medical-insurance-costs" class="level1">
<h1>U.S. Medical Insurance Costs</h1>
<section id="purpose-of-this-project" class="level2">
<h2 class="anchored" data-anchor-id="purpose-of-this-project">Purpose of this Project</h2>
<p>This project focuses on the medical insurance industry. I demonstrate the ability to provide visualizations and statistical inferences when given a cleaned up data set. Here is the data set source: https://www.kaggle.com/datasets/mirichoi0218/insurance</p>
<p>Here are a few questions I formulated before diving into the data set: <em>What single component causes the most increase in insurance costs? What variables play a role in increasing or decreasing insurance costs? What would be the ideal individual to minimize the cost of medical insurance?</em></p>
<p>I look into <strong>smokers</strong> as being a variable of interest. Additionally, I dive into the difference of between male and female insurance costs for both smokers and nonsmokers.</p>
<p><strong>If you wish to skip towards the results portion, feel free to scroll down and have a quick read! Interesting results were found.</strong></p>
<section id="set-up-and-importing-the-data" class="level3">
<h3 class="anchored" data-anchor-id="set-up-and-importing-the-data">Set Up and Importing the Data</h3>
<div class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520</code></pre>
</div>
</div>
</section>
</section>
<section id="analyzing-smoker-insurance-costs" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-smoker-insurance-costs">Analyzing Smoker Insurance Costs</h2>
<p>We want to know what influences the cost of insurance. What causes an individual to pay more for their insurance? We can infer that being a smoker will drastically increase their out of pocket medical insurance expenses.</p>
<p>I take a look into how many smokers we have in this data set. Then, I take a quick look into the smokers’ distribution of charges and show a boxplot to visualize the insurance cost quartiles. Next, I dive into using some statistics such as finding the min, max, mean, median, etc. I follow up by seperating male and female smokers and seeing if there’s a drastic change in their expenses.</p>
<section id="histogram-plot-of-smokers-vs-nonsmokers" class="level3">
<h3 class="anchored" data-anchor-id="histogram-plot-of-smokers-vs-nonsmokers">Histogram Plot of Smokers vs Nonsmokers</h3>
<ul>
<li>Smoker Count: 274</li>
<li>Nonsmoker Count: 1064</li>
</ul>
<div class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-3-output-1.png" width="691" height="498"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="boxplot-and-histogram-distribution-of-insurance-costs-for-smokers" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-and-histogram-distribution-of-insurance-costs-for-smokers">Boxplot and Histogram Distribution of Insurance Costs for Smokers</h3>
<p>The interquartile range is $20,125.33. Very high spread from the first and third interquartiles.</p>
<p>Now, notice that we have a bimodal distribution. This means that there is a variable in the data set that is drastically affecting the insurance cost. Since there is two “humps” we must identify the component that causes a further jump in insurance costs for those who smoke.</p>
<p>What could cause this? - Region? - Bmi? - Sex? - Children? - Age?</p>
<div class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-4-output-1.png" width="710" height="520"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="insurance-cost-statistics-for-smokers" class="level3">
<h3 class="anchored" data-anchor-id="insurance-cost-statistics-for-smokers">Insurance Cost Statistics for Smokers</h3>
<p>Summary Stats: - Mean: $32,050.23 - Median: $34,456.35 - Max: $63,770.43 - Min: $12,829.46 - Standard Deviation: $11,520.47 - Variance: 132721153.14</p>
<p>Given the distribution, we can say that the mean represents the true average insurance cost for smokers.</p>
</section>
<section id="seperating-male-and-female-smokers" class="level3">
<h3 class="anchored" data-anchor-id="seperating-male-and-female-smokers">Seperating Male and Female Smokers</h3>
<p>I chose to seperate male and female smokers to see if there was a noticable difference in cost. Notice in the graphs below, that we can easily identify the culprit for the bimodal distribution. The <strong>BMI</strong> drastically influences the insurance cost when it is greater than or equal to 30 (the obese rating starts at 30 forward). <em>This means that being obese AND being a smoker can sharply increase your medical insurance cost.</em></p>
<p>Note: As <strong>Age</strong> slowly increases, the insurance cost also slowly increases. So, there is a gradual increase in insurance cost as you age. That is common sense since as one ages, one develops more health issues as they near death.</p>
</section>
<section id="analyzing-male-smokers" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-male-smokers">Analyzing Male Smokers</h3>
<p><strong>Graph One</strong>: Cost Distribution - Bimodal Distribution is again present. - Two clusters of cost are due to an underlying variable.</p>
<p><strong>Graph Two</strong>: Barplot of Average Cost per Child - No clear trend. - Only valuable note is that having 4 children seems to have an overall lower average insurance cost.</p>
<p><strong>Graph Three</strong>: Scatterplot of Cost vs BMI with Region - There is a visable linear relationship between BMI and Cost. - There are two clusters of individuals but follows the linear relationship. - At &gt;=30 BMI, there is a clear signifcant increase in insurance cost for male smokers. - Note: a BMI of 30 or implies that the individual is “obese” (though, BMI is not necessarily a good measurement–see results). - No trends with the region.</p>
<p><strong>Graph Four</strong>: Scatterplot of Cost vs Age with Children - There is a linear trend, but split into two linear clusters. - As found earlier, this is most likely due to BMI differences in the indivduals. - Overtime, an individual’s insurance cost will increase as expected.</p>
<p><strong>Graph Five</strong>: Barplot of Average Cost per Region - No valuable insights can be drawn.</p>
<p><strong>Graph Six</strong>: Boxplot of Male Smoker Insurance Cost - Noteworthy to see the spread of male smokers’ insurance cost.</p>
<div class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-6-output-1.png" width="915" height="533"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="bmi-graph-highlighted" class="level3">
<h3 class="anchored" data-anchor-id="bmi-graph-highlighted">BMI Graph Highlighted</h3>
<p>As mentioned above, the reason why the cost distribution had two clusters was due to the difference in BMI in each male smoker. Male smokers with a BMI &gt;= 30 will that their expense increase by approximately 47%.</p>
<div class="cell" data-execution_count="6">
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>Text(0, 0.5, 'Insurance Costs (USD)')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-7-output-2.png" width="660" height="509"></p>
</div>
</div>
</section>
<section id="analyzing-female-smokers" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-female-smokers">Analyzing Female Smokers</h3>
<p><strong>Graph One</strong>: Cost Distribution - Bimodal Distribution is again present. - Two clusters of cost are due to an underlying variable.</p>
<p><strong>Graph Two</strong>: Barplot of Average Cost per Child - No clear trend. - Only valuable note is that having 5 children seems to have an overall lower average insurance cost.</p>
<p><strong>Graph Three</strong>: Scatterplot of Cost vs BMI with Region - There is a visable linear relationship between BMI and Cost - There are two clusters of individuals but follows the linear relationship. - At &gt;=30 BMI, there is a clear signifcant increase in insurance cost for female smokers. - Note: a BMI of 30 or implies that the individual is “obese” (though, BMI is not necessarily a good measurement–see results). - No trends with the region.</p>
<p><strong>Graph Four</strong>: Scatterplot of Cost vs Age with Children - There is a linear trend, but split into two linear clusters. - As found earlier, this is most likely due to BMI differences in the indivduals. - Overtime, an individual’s insurance cost will increase as expected.</p>
<p><strong>Graph Five</strong>: Barplot of Average Cost per Region - No valuable insights can be drawn.</p>
<p><strong>Graph Six</strong>: Boxplot of Female Smoker Insurance Cost - Noteworthy to see the spread of female smokers’ insurance cost.</p>
<p>Given that the Insurane Cost vs BMI is essentially the same as male smokers, the stated results will apply here.</p>
<div class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-9-output-1.png" width="916" height="534"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="average-insurance-cost-comparision-of-male-and-female-smokers" class="level3">
<h3 class="anchored" data-anchor-id="average-insurance-cost-comparision-of-male-and-female-smokers">Average Insurance Cost Comparision of Male and Female Smokers</h3>
<p>Noteworthy mention: - Male smokers pay approximately 1.34% more than their female counterparts when their BMI less than 30. - Male smokers pay approximately 1.42% less than their female counterparts when their BMI greater than or equal to 30.</p>
<div class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-11-output-1.png" width="691" height="495"></p>
</div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>&lt;function matplotlib.pyplot.clf()&gt;</code></pre>
</div>
</div>
</section>
<section id="boxplot-and-histogram-distribution-of-insurance-costs-for-nonsmokers" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-and-histogram-distribution-of-insurance-costs-for-nonsmokers">Boxplot and Histogram Distribution of Insurance Costs for Nonsmokers</h3>
<p>The interquartile range is $7,378.07. Spread is minimal from the first and third interquartiles.</p>
<p>Now, notice that we have a right-skewed distribution.</p>
<p>What could cause this? - Region? - Bmi? - Sex? - Children? - Age?</p>
<p>Keep in mind, there is a chance that we may not be able to determine the cause of those outliers.</p>
<div class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>7378.07</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-12-output-2.png" width="684" height="494"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="analyzing-the-insurance-cost-of-nonsmokers" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-the-insurance-cost-of-nonsmokers">Analyzing the insurance cost of nonsmokers</h2>
<p>Now let’s look at the nonsmokers.</p>
<p>Summary Stats: - Mean: $8,434.27 - Median: $7,345.41 - Max: $39,910.61 - Min: $1,121.87 - Standard Deviation: $5,990.96 - Variance: 35891656</p>
<section id="analyzing-male-nonsmokers" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-male-nonsmokers">Analyzing Male Nonsmokers</h3>
<p><strong>Graph One</strong>: Cost Distribution - Right-skewed distribution is again present. - Knowing this, we should go with the median as the most appropriate statistic instead of the mean.</p>
<p><strong>Graph Two</strong>: Barplot of Average Cost per Child - There seems to be a trend that having more children will lead to higher average insurance costs. - Given the information from the smokers, when an individual has 5 children or more, their insurance costs drops signifcantly. - However, the lowest average comes from having no children at all.</p>
<p><strong>Graph Three</strong>: Scatterplot of Cost vs BMI with Region - There is no correlation between cost and BMI of nonsmokers. - This is an interesting finding. - No trends with the region.</p>
<p><strong>Graph Four</strong>: Scatterplot of Cost vs Age with Children - Strong linear relationship between insurance cost and age. - A secondary trend is shown with the number of children. - The less children, the insurance cost is on the lower end of the linear relationship. - The more children, the insurance cost is on the higher end of the linear relationship - The outliers do not follow the trend line.</p>
<p><strong>Graph Five</strong>: Barplot of Average Cost per Region - No valuable insights can be drawn. - Some regions are simply cheaper than others.</p>
<p><strong>Graph Six</strong>: Boxplot of Male Smoker Insurance Cost - Noteworthy to see the spread of male smokers’ insurance cost.</p>
<div class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-14-output-1.png" width="915" height="533"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
<div class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-15-output-1.png" width="732" height="522"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
<section id="analyzing-female-nonsmokers" class="level3">
<h3 class="anchored" data-anchor-id="analyzing-female-nonsmokers">Analyzing Female Nonsmokers</h3>
<p><strong>Graph One</strong>: Cost Distribution - Right-skewed distribution is again present. - Knowing this, we should go with the median as the most appropriate statistic instead of the mean.</p>
<p><strong>Graph Two</strong>: Barplot of Average Cost per Child - Similar to the male nonsmokers, there seems to be a trend that having more children will result in higher average insurance costs. - Given the information from the smokers, when an individual has 5 children or more, their insurance costs drops on average. - However, the lowest average comes from having no children at all.</p>
<p><strong>Graph Three</strong>: Scatterplot of Cost vs BMI with Region - Again, there is no correlation between cost and BMI of nonsmokers. - No trends with the region.</p>
<p><strong>Graph Four</strong>: Scatterplot of Cost vs Age with Children - Strong linear relationship between insurance cost and age. - A secondary trend is shown with the number of children. - The less children, the insurance cost is on the lower end of the linear relationship. - The more children, the insurance cost is on the higher end of the linear relationship - The outliers do not follow the trend line.</p>
<p><strong>Graph Five</strong>: Barplot of Average Cost per Region - There is a slight trend of region importance. - The northeast is more expensive on average than the southwest.</p>
<p><strong>Graph Six</strong>: Boxplot of Male Smoker Insurance Cost - Noteworthy to see the spread of male smokers’ insurance cost.</p>
<div class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-16-output-1.png" width="915" height="533"></p>
</div>
<div class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="nonsmokers-vs-smokers" class="level1">
<h1>Nonsmokers vs Smokers</h1>
<div class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>The average insurance cost for a nonsmoker male is $8087.2.
The average insurance cost for a nonsmoker female is $8762.3.
The average difference in insurance cost for nonsmoker male and female is $675.1.

The nonsmoker males are charged 4.01% less than their female counterpart.

The average insurance cost for a smoker male is $33042.01.
The average insurance cost for a smoker female is $30679.0.
The average difference in insurance cost for smoker male and female is $2363.01.

The smoker males are charged 3.71% more than their female counterpart.

On average, a male nonsmoker pays $8087.2, while a female smoker pays $33042.01.
The difference in their insurance charges is $24954.81.
A male smoker will get charged approxmiately 408.57% more than a nonsmoker.

On average, a female nonsmoker pays $8762.3, while a female smoker pays $30679.0.
The difference in their insurance charges is $21916.7.
A female smoker will get charged approxmiately 350.12% more than a nonsmoker.</code></pre>
</div>
</div>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>It is clear that smoking will increase your health insurance charges. Male and female smokers will receive an additional charge for having a BMI equal or greater than 30. Male smokers hitch a 52% increase while female smokers endure a 49% increase. Keep in mind that this apart from their base premium increase for being smokers in the first place. To emphasize, male smokers will approximately be charged 408.57% more than their nonsmoker counterpart. Similarly, female smokers approximately pay 350.12% more than their nonsmoker counterparts. Given the data, it pushes the idea that smoking and being in an unhealthy body mass index will punish those individuals through higher health insurance charges. Note: Overtime, health insurance does get slightly more expensive as we age.</p>
<p>There is much more to be done with this project. I may come back to it and do some machine learning methods to predict if this sample represents the entire population or not.</p>
<p>I included two articles: One states that BMI metric is an inaccurate method to measure human height and weight; the other confirms that tabacco usage allows insurance companies to charge those individuals a premium.</p>
<p>“BMI (body mass index), which is based on the height and weight of a person, is an inaccurate measure of body fat content and does not take into account muscle mass, bone density, overall body composition, and racial and sex differences”</p>
<p>(source: https://www.medicalnewstoday.com/articles/265215)</p>
<p>“The practice of charging tobacco users more is called tobacco rating. The ACA allows for insurance companies to charge smokers up to 50% more (or premiums that are 1.5 times higher) than non-smokers through a tobacco surcharge.”</p>
<p>(source: https://www.healthmarkets.com/content/smoking-and-health-insurance)</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>